name: Build and release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations.
      fail-fast: false

      # Set up a matrix to run the following configurations:
      # 1. <Linux, Release, latest Clang compiler toolchain on the default runner image, default generator>
      # 2. <Windows, Release, latest MSVC compiler toolchain on the default runner image, default generator>
      matrix:
        os: [ubuntu] # add "windows" to build on windows
        build_type: [Release]
        c_compiler: [clang, cl]
        include:
          #- os: windows
          #  c_compiler: cl
          #  cpp_compiler: cl
          - os: ubuntu
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          #- os: windows
          #  c_compiler: clang
          - os: ubuntu
            c_compiler: cl

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Install clang 14
      run: sudo apt install clang && clang -v
    - name: Configure CMake
      run: >
        cmake -B ${{ github.workspace }}/build
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }} -Wno-dev
    - name: Cache cmake
      uses: actions/cache@v3
      with:
        path: build/libs
        key: ${{ runner.os }}.${{ hashFiles('libs') }}
        restore-keys: ${{ runner.os }}.
    - name: Build project
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}
    - name: Move library file
      run: mv build/libStevEngine.a libStevEngine.a
    - name: Deploy to output branch
      uses: EndBug/add-and-commit@v9
      with:
        add: "build/libStevEngine.a"
        new_branch: output