name: Generate documentation

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Install doxygen
      run: sudo apt install doxygen
    - name: Generate documentation site
      run: doxygen
    - name: Deploy to gh-pages branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: ./doxygen/html
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}